server:
  port: ${PORT:8762}

eureka:
  instance:
    preferIpAddress: true
    hostname: ${HOSTNAME:localhost}

  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

spring:
  application:
    name: GateWay-rdp
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins: ${ALLOWED_ORIGINS:*}
                allowedHeaders: "*"
                allowedMethods:
                      - POST

management:
  endpoint:
    gateway:
      access: unrestricted
  endpoints:
    web:
      exposure:
        include:
          - '*'